services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb
  # grafana:
  #   image: grafana/grafana-oss
  #   container_name: grafana
  #   user: "1000"
  #   volumes:
  #     - ./grafana:/var/lib/grafana
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mariadb
  #   environment:
  #     GF_SERVER_PROTOCOL: http
  #     GF_SERVER_ROOT_URL: http://${DOMINIO}:${PUERTO}
  #     # GF_SERVER_ROOT_URL: http://${DOMINIO}:${PUERTO}/grafana/
  #     # GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  #     GF_SERVER_DOMAIN: https://${DOMINIO}/
  #     GF_ANALYTICS_REPORTING_ENABLED: "false"
  #   restart: unless-stopped
  app:
    image: app
    build:
      context: ./app
    container_name: app
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=${MARIADB_HOST}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./app/static:/var/www/html/static:ro  
    links:
      - app:produccion 
    depends_on:
      - app

