services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PUID=1000
      - PGID=1000
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}      
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    ports:
      - 3306:3306
    restart: unless-stopped
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb
      
  app:
    image: app
    build:
      context: ./app
    container_name: app
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - MARIADB_HOST=${MARIADB_HOST}
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - mariadb